### PR TITLE
Added Promise wrap to async methods

### LINKED ISSUE #36: Use Promises instead of callbacks?
Why are async methods not using promises instead of callbacks? It would be so much easier to use these methods.

Thanks,
Nick

### PR DESCRIPTION
**Pull request by SwordSoul**
`hash`, `genSalt` and `compare` methods now return a Promise if called without a callback.

fixes #36

### CODE REVIEW

**Comment by dcodeIO** [comment]
Won't this break in older browsers?

**Comment by SwordSoul** [comment]
Added a type check for Promise availability.

**Comment by dcodeIO** [comment]
Ok, something else: Can't we just return a promise from the respective method in case the callback argument has been omitted? This way around, it would of course throw in environments where promises aren't supported, but that'd be ok as the method has already been invoked with invalid arguments for that environment. Wouldn't that reduce overhead?

**Comment by SwordSoul** [comment]
Thanks for the update!
You can also update README:
for hash if progressCallback is provided and callback is set to null then progressCallback will work along with promise

**Pull request closed without merging**
