### PR TITLE
Issue #66 -  Fix invalid JSON in bower.json generation

### PR DESCRIPTION
**Pull request by delanni**
## Reason for change?
See Issue #66 
A good number of us uses flow for type-checking our javascript code. If this library is sneaking in as a chain dependency, then our flow static checks fail on the invalid .json format. The .json file is used as a template, but it's not noted in the file format, so any checker will fail trying to parse it.

## What changed?
- post-fixed the file name with a `.template` suffix
- patched the generator to use the new template filename
- bumped the patch version

### CODE REVIEW

**Comment by dcodeIO** [comment]
Thanks, looking good!

**Comment by mjomble** [comment]
Hi, is there an estimate of when version 2.4.4 with this change will be released and published on npm?

**Comment by mjomble** [comment]
@dcodeIO is anything blocking the release of 2.4.4?

**Comment by RDGthree** [comment]
@dcodeIO u serious

**Comment by michaelschiff** [comment]
This appears to still be an issue - any update on the release of 2.4.4 ?

**Pull request merged**
